### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by Vince-bleu** [b00f/gnome-clipboard#1]
Hi,
Thanks for your extension, it looks promising.
It work for copy and paste, i can delete items...
I'm using manjaro and I have a problem to access the configuration window. I got the message "Technical problem"
Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/home/vince/.local/share/gnome-shell/extensions/gnome-clipboard@b00f.github.io/prefs.js:16:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Any idea ?

**Comment by 001101** [comment]
same

The settings of extension gnome-clipboard@b00f.github.io had an error:
```
Error: No property margin on GtkBox
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
buildPrefsWidget@/home/p1/.local/share/gnome-shell/extensions/gnome-clipboard@b00f.github.io/prefs.js:16:15
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by b00f** [comment]
@Vince-bleu and @001101 

Please check the latest version. Hopefully this is fixed. I don't have gnome 40, so I can't test it.

**Comment by Vince-bleu** [comment]
Still got the error with the latest version :-(
Using Gnome 40 (forgot to tel) on manjaro.

**Comment by b00f** [comment]
Not sure when I can fix it. Sorry for the inconvenience.
