### ISSUE TITLE
Crash gnome-shell 42 on copy

### ISSUE THREAD

**Issue by realgrm** [b00f/gnome-clipboard#11]
It crash randomly when I copy something.
Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2071410

System Info: 
Fedora Linux 36.20220402.n.0 (Silverblue Prerelease)
gnome-shell-42.0-2.fc36
kernel 5.17.1-300.fc36.x86_64

**Comment by realgrm** [comment]
I opened this issue because the file bellow generated by abrt (Fedora's Automatic bug detection and reporting tool) pointed various messages from this extension. 
https://bugzilla.redhat.com/attachment.cgi?id=1870483

**Comment by b00f** [comment]
@realgrm turn on the `Read clipboard by timer` settings. This should prevent the crash. Hopefully.

**Comment by b00f** [comment]
@realgrm I think it is fixed [here](https://github.com/b00f/gnome-clipboard/commit/0d53dbb09df84f8f3793b7e6b5d4e8b44949fa8f). We should not call `_init` directly. Please check the latest version.

**Comment by realgrm** [comment]
Hi, sorry for the hiatus. Well, the issue does not occur anymore. Closing this issue.
