### ISSUE TITLE
Support for gnome 42

### ISSUE THREAD

**Issue by zhuohoudeputao** [b00f/gnome-clipboard#13]

**Comment by b00f** [comment]
@zhuohoudeputao any contributions are most welcome

**Comment by b00f** [comment]
@zhuohoudeputao done. Install the latest extension: https://extensions.gnome.org/extension/4422/gnome-clipboard/

**Comment by zhuohoudeputao** [comment]
@b00f Thanks for your hard working! It's now working on Gnome 42.
