### ISSUE TITLE
UI issue, the pin button are hidden and small

### ISSUE THREAD

**Issue by hungtooc** [b00f/gnome-clipboard#17]
The pin button are hidden and small, only see when mouse cursor over. I spent 2 days to figure out how to pin

**Comment by b00f** [comment]
@hungtooc thanks fro reporting it. Could you please attach a screenshot.

**Comment by hungtooc** [comment]
> @hungtooc thanks fro reporting it. Could you please attach a screenshot.
- when mouse not over, i doesn't see the pin button
![Screenshot from 2022-09-09 13-18-15](https://user-images.githubusercontent.com/24487114/189284379-91d9bbc0-c945-44ee-92a7-aa0328fea3ca.png)
- when mouse over, it's still small to see it
![Screenshot from 2022-09-09 13-18-52](https://user-images.githubusercontent.com/24487114/189284482-576357d2-ede9-4bd5-942b-c5362e16e6df.png)

I'm using ubuntu 22.04

**Comment by b00f** [comment]
A pinned item is an item that has a Pin icon. So it works as intended. We purposely doesn't show the pin icon for non-pinned items. 
Do you have any other idea to distinguish between Pin and non-Pinned items?

**Comment by hungtooc** [comment]
I used to use this extention since ubuntu 20.04, but couldn'd use it anymore when I upgrade my OS to 22.04. So "gnome-clipboard" become my choose now. 
![image](https://user-images.githubusercontent.com/24487114/189291384-9c165f27-e06f-4012-bf65-d12ab67042fb.png)
they distinguish by black/white star.
I think "gnome-clipboard" is little hard for newbie.
