### ISSUE TITLE
"Cut" removes too many lines

### ISSUE THREAD

**Issue by bbbenji** [b00f/gnome-clipboard#24]
When cutting selected text `Ctrl+X`, too much text is cut out, beyond whatever is selected. Especially happens in VSC.

Disabling the extension resolved the issue. Not sure if Gnome 43 related.

Selected text to be cut:
![Screenshot from 2022-11-22 12-23-08](https://user-images.githubusercontent.com/1678118/203302248-a20675bc-c4f0-4c5b-8382-829203456e8c.png)

Result after cutting selected text `Ctrl+X`:
![Screenshot from 2022-11-22 12-23-22](https://user-images.githubusercontent.com/1678118/203302244-50d5b475-5140-43ff-868c-06d67234e0fe.png)

Expected result:
![Screenshot from 2022-11-22 12-23-28](https://user-images.githubusercontent.com/1678118/203302238-0d65b48c-1c41-496d-b08b-be24298bf2c6.png)

**Comment by b00f** [comment]
Interesting! I am surprised because we just read the clipboard. I try to reproduce it and ix it

**Comment by bbbenji** [comment]
Agreed, it's very interesting. I've had to extension off since creating this issue and re-enabled it just now to see if it still happens. Yes, it still happens.

Is there anything I can do to debug the issue myself?

**Comment by b00f** [comment]
@bbbenji Enable "Read clipboard by time" and if it doesn't happen again, at least we now the clipboard call back has issue.

**Comment by bbbenji** [comment]
@b00f enabling "Read clipboard by timer" resolves the issue. It now works as it should.

**Comment by b00f** [comment]
So we know the Clipboard listener has issue. Probably we should report it
