### ISSUE TITLE
Clipboard content in log

### ISSUE THREAD

**Issue by microniko** [b00f/gnome-clipboard#7]
Hello,
Fortuitously, I see this in `/var/log/syslog` : 

```
Dec 18 10:05:47 carbone gnome-shell[2657]: Gnome Clipboard:  [INFO] set clipboard content: *****
```

With the content clipboard. It is very unsecured if this content is a password.

OS : Debian Bullseye.

**Comment by b00f** [comment]
Hi, This is a good point. We have to disable the log before releasing the extension.

**Comment by microniko** [comment]
Or simply do not log the content.

**Comment by b00f** [comment]
Logging is useful for debugging. We can disable it in production. Any contribution is appreciated
