### ISSUE TITLE
`make install` fails with Error 2

### ISSUE THREAD

**Issue by bouncinglime** [b00f/gnome-clipboard#9]
Hello -

I am unable to install from extensions.gnome.org I think due to issues with Firefox and snap (see https://github.com/keepassxreboot/keepassxc-browser/issues/1426 for more info and a similar broken situation). I have run the steps for manual install

```
git clone https://github.com/b00f/gnome-clipboard.git``
cd gnome-clipboard
make install
```

but I get the following error :
```
$ make install
sh scripts/transpile.sh
scripts/transpile.sh: 22: tsc: not found
find: ‘src/build’: No such file or directory
Missing extension.js in extension pack
make: *** [Makefile:21: pack] Error 2
```

Any suggestions?

OS : Pop!_OS 21.10
GNOME : 40.4.0
Firefox : 96.0

Thank you.

**Comment by b00f** [comment]
Did you install Typescript: 'npm install typescript'

**Comment by bouncinglime** [comment]
This can be closed; apologies for the very belated reply. I fixed the issue by disabling [apparmor](https://help.ubuntu.com/community/AppArmor) for firefox; I hadn't realized it was running for more than just Zoom.
